Repository CONP-PCNO/conp-portal, pull requests merged in 2019-09, with the labels that each got.

#79 Patch for broken db migration
  conp.py
  test/__init__.py
Labels: bug

#80 Pep8 compliance
  .travis.yaml
  app/__init__.py
  app/admin/__init__.py
  app/admin/routes.py
  app/auth/__init__.py
  app/auth/routes.py
  app/forms.py
  app/forums/__init__.py
  app/forums/routes.py
  app/main/__init__.py
  app/main/routes.py
  app/models.py
  app/oauth.py
  app/pipelines/__init__.py
  app/pipelines/routes.py
  app/profile/__init__.py
  app/profile/routes.py
  app/search/__init__.py
  app/search/routes.py
  app/threads.py
  config.py
  requirements.txt
Labels: blocked, enhancement

#81 Made several changes to make getting up and running with a test environment easier.
  .flaskenv.sample
  .gitignore
  README.md
  app/cli.py
  config.py
  conp.py
  flaskenv.template
  migrations/versions/063cdaf656b3_.py
  run.py
Labels: DOCUMENTATION, enhancement, new-feature

#84 Initial implementation of PyTest Framework
  .travis.yml
  README.md
  app/__init__.py
  config.py
  conp.py
  requirements.txt
  tests/__init__.py
  tests/blueprint_specific_tests/main_bp_tests/test_main_endpoints.py
  tests/conftest.py
  tests/database_tests/test_migrations.py
  tests/unit_tests/test_dataset_model.py
  tests/unit_tests/test_user_model.py
Labels: new-feature, passed-manual-test, testing

#88 [ADD] Styleguide for user interface
  app/__init__.py
  app/static/css/core.css
  app/static/css/styleguide.css
  app/styleguide/__init__.py
  app/styleguide/routes.py
  app/templates/styleguide.html
Labels: UI, enhancement

#94 Loc #89
  README.md
  app/admin/routes.py
  app/forums/routes.py
  app/pipelines/routes.py
  app/search/routes.py
  tests/blueprint_specific_tests/admin_bp_tests/test_admin_endpoints.py
  tests/blueprint_specific_tests/auth_bp_tests/test_auth_endpoints.py
  tests/blueprint_specific_tests/forums_bp_tests/test_forums_endpoints.py
  tests/blueprint_specific_tests/pipelines_bp_tests/test_pipelines_endpoints.py
  tests/blueprint_specific_tests/profile_bp_tests/test_profile_endpoints.py
  tests/blueprint_specific_tests/search_bp_tests/test_search_endpoints.py
  tests/conftest.py
  tests/unit_tests/test_dataset_model.py
  tests/unit_tests/test_user_model.py
Labels: testing
