Repository CONP-PCNO/conp-portal, pull requests merged in 2019-04, with the labels that each got.

#21 [ADD] DataTable wrapper to handle ajax
  app/routes.py
  app/static/css/custom.css
  app/static/lib/conp-react/package-lock.json
  app/static/lib/conp-react/package.json
  app/static/lib/conp-react/src/AppContext/index.js
  app/static/lib/conp-react/src/DataTable/DataTable.js
  app/static/lib/conp-react/src/DataTable/DataTableContainer.js
  app/static/lib/conp-react/src/DataTable/index.js
  app/static/lib/conp-react/src/DatasetElement/index.js
  app/static/lib/conp-react/src/PipelineElement/index.js
  app/static/lib/conp-react/src/data-table/DataTable.js
  app/static/lib/conp-react/src/data-table/DataTableAJAX.js
  app/static/lib/conp-react/src/data-table/index.js
  app/static/lib/conp-react/src/index.js
  app/static/lib/conp-react/umd/1.conp-react.js
  app/static/lib/conp-react/umd/1.conp-react.min.js
  app/static/lib/conp-react/umd/1.conp-react.min.js.map
  app/static/lib/conp-react/umd/conp-react.js
  app/static/lib/conp-react/umd/conp-react.min.js
  app/static/lib/conp-react/umd/conp-react.min.js.map
  app/templates/search.html
Labels: UI, enhancement, passed-manual-test

#22 [Dashboard] Improve dashboard landing page UI
  app/static/css/custom.css
  app/templates/about.html
  app/templates/admin.html
  app/templates/base.html
  app/templates/base_public.html
  app/templates/contact.html
  app/templates/fragments/admin_sidebar.html
  app/templates/index.html
  app/templates/index_visitor.html
  app/templates/public.html
  app/templates/search.html
  app/templates/share.html
Labels: UI, enhancement, new-feature, passed-manual-test

#28 [Bug] Vulnerability fix
  requirements.txt
Labels: bug

#27 [Registration] Add registration page on CONP
  README.md
  app/forms.py
  app/models.py
  app/oauth.py
  app/routes.py
  app/static/css/login.css
  app/templates/base.html
  app/templates/base_login.html
  app/templates/base_public.html
  app/templates/fragments/public_sidebar.html
  app/templates/index.html
  app/templates/login.html
  app/templates/register.html
  migrations/versions/b6335c811e2a_.py
  run.py
Labels: enhancement, new-feature, passed-manual-test

#31 [Portal] Some bug fixes
  app/routes.py
  app/templates/base_public.html
  app/templates/fragments/admin_sidebar.html
  app/templates/fragments/sidebar.html
  app/templates/index.html
  app/templates/public.html
  app/templates/search.html
  requirements.txt
Labels: passed-manual-test

#32 [Portal] fix navbar brand link
  app/templates/base.html
  app/templates/base_public.html
  app/templates/index.html
  app/templates/public.html
  app/templates/search.html
Labels: passed-manual-test

#38 [Bug Fix] fix some styling issues
  app/routes.py
  app/static/css/custom.css
  app/static/img/conp.png
  app/templates/dataset.html
  app/templates/index.html
  app/templates/public.html
  app/templates/search.html
Labels: UI, enhancement, passed-manual-test

#11 [Documentation] Add Readthedocs
  docs/Makefile
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/html/.buildinfo
  docs/build/html/_sources/index.rst.txt
  docs/build/html/_static/ajax-loader.gif
  docs/build/html/_static/alabaster.css
  docs/build/html/_static/basic.css
  docs/build/html/_static/comment-bright.png
  docs/build/html/_static/comment-close.png
  docs/build/html/_static/comment.png
  docs/build/html/_static/custom.css
  docs/build/html/_static/doctools.js
  docs/build/html/_static/documentation_options.js
  docs/build/html/_static/down-pressed.png
  docs/build/html/_static/down.png
  docs/build/html/_static/file.png
  docs/build/html/_static/jquery-3.2.1.js
  docs/build/html/_static/jquery.js
  docs/build/html/_static/language_data.js
  docs/build/html/_static/minus.png
  docs/build/html/_static/plus.png
  docs/build/html/_static/pygments.css
  docs/build/html/_static/searchtools.js
  docs/build/html/_static/underscore-1.3.1.js
  docs/build/html/_static/underscore.js
  docs/build/html/_static/up-pressed.png
  docs/build/html/_static/up.png
  docs/build/html/_static/websupport.js
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/objects.inv
  docs/build/html/search.html
  docs/build/html/searchindex.js
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
Labels: DOCUMENTATION, passed-manual-test
