Repository CONP-PCNO/conp-portal, pull requests merged in 2020-06, with the labels that each got.

#297 Update npm packages to fix vulnerabilities
  app/static/lib/conp-react/package-lock.json
  app/static/lib/conp-react/package.json
  app/static/lib/conp-react/umd/1.conp-react.js
  app/static/lib/conp-react/umd/1.conp-react.min.js
  app/static/lib/conp-react/umd/1.conp-react.min.js.map
  app/static/lib/conp-react/umd/conp-react.js
  app/static/lib/conp-react/umd/conp-react.min.js
  app/static/lib/conp-react/umd/conp-react.min.js.map
Labels: dependencies

#305 This will add an about page to the portal (W
  app/main/routes.py
  app/static/img/CONP-datasets.png
  app/static/img/CONP-features.png
  app/templates/about.html
  app/templates/fragments/navigation_bar.html
  app/templates/index.html
Labels: blocked, enhancement, in-progress, priority-high

#308 Add sponsors and partners links to the dashboard
  app/templates/about.html
  app/templates/index.html
Labels: enhancement

#313 Derived datasets - add tags for parent datasets
  app/search/models.py
  app/search/routes.py
  app/templates/dataset.html
Labels: enhancement, passed-manual-test

#320 Dataset CircleCI badge links to summary builds page
  app/static/lib/conp-react/src/DatasetElement/index.js
  app/static/lib/conp-react/umd/conp-react.js
  app/static/lib/conp-react/umd/conp-react.min.js
  app/static/lib/conp-react/umd/conp-react.min.js.map
Labels: passed-manual-test
