Repository CONP-PCNO/conp-portal, pull requests merged in 2020-10, with the labels that each got.

#356 Change the site ID to 2 in config.py
  config.py
Labels: bug

#361 fixes KeyError: `DEPRECATED`
  app/pipelines/routes.py
Labels: hacktoberfest-accepted

#362 Read URL of CBRAIN from JSON file instead of hardcoding it to login URL
  app/pipelines/routes.py
Labels: hacktoberfest-accepted, passed-manual-test
