Repository CONP-PCNO/conp-portal, pull requests merged in 2020-04, with the labels that each got.

#232 remove ability to dismiss terms dialog
  app/templates/common/base_main.html
Labels: passed-manual-test

#234 set page=1 on search term change
  app/static/lib/conp-react/src/DataTable/DataTable.js
  app/static/lib/conp-react/umd/conp-react.js
  app/static/lib/conp-react/umd/conp-react.min.js
  app/static/lib/conp-react/umd/conp-react.min.js.map
Labels: UI, blocking release, bug, passed-manual-test

#236 [Terms of use] update the terms of use to the latest version
  app/templates/common/base_main.html
Labels: blocking release, bug

#243 add faq page, fetch content from github
  app/main/routes.py
  app/templates/faq.html
  app/templates/fragments/sidebar.html
Labels: UI, enhancement

#244 open external links in new tab
  app/static/lib/conp-react/src/DatasetElement/index.js
  app/static/lib/conp-react/src/PipelineElement/index.js
  app/static/lib/conp-react/umd/conp-react.js
  app/static/lib/conp-react/umd/conp-react.min.js
  app/static/lib/conp-react/umd/conp-react.min.js.map
  app/templates/dataset.html
  app/templates/pipelines.html
Labels: passed-manual-test

#249 Alan's feedback on the terms of use
  app/templates/common/base_main.html
Labels: blocking release

#250 Remove the year from the footer of HTML pages
  app/templates/fragments/footer.html
Labels: UI, enhancement

#233 Fix the README.md instructions
  README.md
Labels: DOCUMENTATION

#251 Clarifying dataset download instructions
  app/templates/dataset.html
Labels: DOCUMENTATION, UI, enhancement

#219 Disable grey cbrain
  app/static/lib/conp-react/src/PipelineElement/index.js
  app/static/lib/conp-react/umd/conp-react.js
  app/static/lib/conp-react/umd/conp-react.min.js
  app/static/lib/conp-react/umd/conp-react.min.js.map
Labels: blocking release, enhancement

#259 Naser's feedback for the terms of use
  app/templates/common/base_main.html
Labels: enhancement

#261 Add the version date of the terms of use
  app/templates/common/base_main.html
Labels: enhancement

#264 add download_metadata only on dataset page
  app/static/lib/conp-react/package-lock.json
  app/static/lib/conp-react/package.json
  app/static/lib/conp-react/src/DatasetElement/index.js
  app/static/lib/conp-react/umd/1.conp-react.js
  app/static/lib/conp-react/umd/1.conp-react.min.js
  app/static/lib/conp-react/umd/conp-react.js
  app/static/lib/conp-react/umd/conp-react.min.js
  app/static/lib/conp-react/umd/conp-react.min.js.map
  app/templates/dataset.html
Labels: passed-manual-test

#269 Fixing spacing between download instructions
  app/templates/dataset.html
Labels: enhancement
