Repository CONP-PCNO/conp-portal, pull requests merged in 2021-04, with the labels that each got.

#381 Download button caching
  app/search/models.py
  app/search/routes.py
  app/templates/dataset.html
  config.py
  deploy/nginx_config/conp-portal
  flaskenv.template
Labels: dataset pages, passed-manual-test

#443 Change Dashboard to Home and add an analytics button
  app/templates/fragments/sidebar.html
Labels: UI

#446 Add https:// in front of matomo URL for the update_analytics function of flask
  app/cli.py
  flaskenv.template
Labels: bug

#448 Query Matomo for download button statistics
  app/cli.py
  app/models.py
  migrations/versions/3d982110f18c_add_matomo_daily_portal_download_summary.py
Labels: analytics
